"""add category

Revision ID: 43036543247d
Revises: 97bb87ddbce1
Create Date: 2018-09-09 10:49:53.519464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43036543247d'
down_revision = '97bb87ddbce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'pitch', ['pitch_id'], ['id'])
    op.add_column('pitch', sa.Column('actual_pitch', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_pitch_title', table_name='pitch')
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    op.drop_column('pitch', 'title')
    op.drop_column('pitch', 'comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_index('ix_pitch_title', 'pitch', ['title'], unique=False)
    op.drop_column('pitch', 'user_id')
    op.drop_column('pitch', 'category')
    op.drop_column('pitch', 'actual_pitch')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'pitch_id')
    # ### end Alembic commands ###
