"""Modified comments column

Revision ID: 973441ebb72c
Revises: a76a7dc6cb81
Create Date: 2018-09-07 15:05:42.634142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973441ebb72c'
down_revision = 'a76a7dc6cb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('comments', sa.String(length=255), nullable=True))
    op.drop_column('pitch', 'statement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('statement', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'comments')
    # ### end Alembic commands ###
